const Lang = {
	ua:{
		id: '№',
		lastName: 'Прізвище',
		name: "Ім'я",
		pob: 'Побатькові',
		rasch_sch: 'Рахунок',
		mfo: 'МФО',
		address:'Адреса',
		ttn: 'ТТН',
		agreement: 'Договір',
		client: 'Замовник',
		product: 'Товар',
		container: 'Контейнер',
		transportKind: 'Вид транспорту',
		button_submit: 'Підтвердити',
		button_add:'Додати',
		searchLastName: 'Пошук за прізвищем',
		deepSearch:'Розширений пошук',
		sortBy:'Сортувати по:',
		normal:'За зростанням',
		reverse:'За спаданням',
		title:'Назва',
		factory:'Завод',
		cost:'Ціна',
		searchName: 'Пошук за назвою',
		Npreisk:'№ прейскуранту',
		auto:'Авто',
		nTrip:'№ доручення/дорожн.листа',
		nAuto:'№ авто',
		driverFIO:'П.І.Б. водія',
		train:'Потяг',
		coachId:'№ вагону',
		trainTicket:'№ залізничного квитка',
		avia:'Літак',
		aviaTicket:'№ квитка на літак',
		searchAgreement: 'Пошук за договором',
		containerCount:'Кількість контейнерів',
		transportSumm:'Сума траспортування',
		p2:'Дод.колонка 1',
		p3:'Дод.колонка 2',
		p4:'Дод.колонка 3',
		clientId:'Замовник',
		creationDate:'Дата заключення',
		summ:'Сума',
		searchClientId:'Пошук за замовником'
	},
	en:{
		id: 'id',
		lastName: 'Lastname',
		name: 'Name',
		pob: 'Patronymic',
		rasch_sch: 'Account',
		mfo: 'MFO',
		address:'Address',
		ttn: 'TTN',
		agreement: 'Agreement',
		client: 'Client',
		product: 'Product',
		container: 'Container',
		transportKind: 'Kind of transport',
		button_submit: 'Submit',
		button_add:'Add',
		searchLastName: 'Search for Lastname',
		deepSearch:'Deep search',
		sortBy:'Sort by criteria:',
		normal:'Normal',
		reverse:'Reverse',
		title:'Name',
		factory:'Factory',
		cost:'Cost',
		searchName: 'Search for name',
		Npreisk:'Id of price-list',
		auto:'Auto',
		nTrip:'Id of trip',
		nAuto:'Id of auto',
		driverFIO:'Driver info',
		train:'Train',
		coachId:'Id of coach',
		trainTicket:'Trainticket',
		avia:'Avia',
		aviaTicket:'Aviaticket',
		searchAgreement: 'Search by agreement',
		containerCount:'Count of containers',
		transportSumm:'Summ of transporting',
		p2:'Column 1',
		p3:'Column 2',
		p4:'Column 3',
		clientId:'Client',
		creationDate:'Date of creation',
		summ:'Summary',
		searchClientId:'Search for client'
	},
	ru:{
		id: '№',
		lastName: 'Фамилия',
		name: 'Имя',
		pob: 'Отчество',
		rasch_sch: 'Счет',
		mfo: 'МФО',
		address:'Адрес',
		ttn: 'ТТН',
		agreement: 'Договор',
		client: 'Клиент',
		product: 'Товар',
		container: 'Контейнер',
		transportKind: 'Вид транспорта',
		button_submit: 'Подтвердить',
		button_add:'Добавить',
		searchLastName: 'Поиск по фамилии',
		deepSearch:'Расширенный поиск',
		sortBy:'Отсортировать по критерию:',
		normal:'По возрастанию',
		reverse:'По уменьшению',
		title:'Название',
		factory:'Завод',
		cost:'Цена',
		searchName: 'Поиск по названию',
		Npreisk:'№ прейскуранта',
		auto:'Авто',
		nTrip:'№ доверенности или путевого листа',
		nAuto:'№ авто',
		driverFIO:'Ф.И.О. водителя',
		train:'Поезд',
		coachId:'№ вагона',
		trainTicket:'ЖД билет',
		avia:'Самолет',
		aviaTicket:'Билета на самолет',
		searchAgreement: 'Поиск по договору',
		containerCount:'Количество контейнеров',
		transportSumm:'Сумма транпортировки',
		p2:'Опц.колонка 1',
		p3:'Опц.колонка 2',
		p4:'Опц.колонка 3',
		clientId:'Заказчик',
		creationDate:'Дата заключения',
		summ:'Сумма',
		searchClientId:'Поиск по заказчику'
		}
};
export default Lang; 