const Lang = {
	ua:{
		id: '№',
		lastName: 'Прізвище',
		name: "Ім'я",
		pob: 'Побатькові',
		rasch_sch: 'Рахунок',
		mfo: 'МФО',
		address:'Адреса',
		ttn: 'ТТН',
		agreement: 'Договір',
		client: 'Клієнт',
		product: 'Товар',
		container: 'Контейнер',
		transport_kind: 'Вид транспорту',
		button_submit: 'Підтвердити',
		button_add:'Додати',
		searchLastName: 'Пошук за прізвищем',
		deepSearch:'Розширений пошук'
	},
	en:{
		id: 'id',
		lastName: 'Lastname',
		name: 'Name',
		pob: 'Patronymic',
		rasch_sch: 'Account',
		mfo: 'MFO',
		address:'Address',
		ttn: 'TTN',
		agreement: 'Agreement',
		client: 'Client',
		product: 'Product',
		container: 'Container',
		transport_kind: 'Kind of transport',
		button_submit: 'Submit',
		button_add:'Add',
		searchLastName: 'Search for Lastname',
		deepSearch:'Deep search'
	},
	ru:{
		id: '№',
		lastName: 'Фамилия',
		name: 'Имя',
		pob: 'Отчество',
		rasch_sch: 'Счет',
		mfo: 'МФО',
		address:'Адрес',
		ttn: 'ТТН',
		agreement: 'Договор',
		client: 'Клиент',
		product: 'Товар',
		container: 'Контейнер',
		transport_kind: 'Вид транспорта',
		button_submit: 'Подтвердить',
		button_add:'Добавить',
		searchLastName: 'Поиск по фамилии',
		deepSearch:'Расширенный поиск'
	}
};
export default Lang; 