import keyMirror from 'keymirror';

export default keyMirror({
    LOAD_PRODUCT_REQUEST: null,
    LOAD_PRODUCT_SUCCESS: null,
    LOAD_PRODUCT_FAIL: null,
    LOAD_CLIENT_REQUEST: null,
    LOAD_CLIENT_SUCCESS: null,
    LOAD_CLIENT_FAIL: null,
    LOAD_CONTAINER_REQUEST: null,
    LOAD_CONTAINER_SUCCESS: null,
    LOAD_CONTAINER_FAIL: null,
    LOAD_TRANSPORT_KIND_REQUEST: null,
    LOAD_TRANSPORT_KIND_SUCCESS: null,
    LOAD_TRANSPORT_KIND_FAIL: null,
    LOAD_AGREEMENT_REQUEST: null,
    LOAD_AGREEMENT_SUCCESS: null,
    LOAD_AGREEMENT_FAIL: null,
    LOAD_TTN_REQUEST: null,
    LOAD_TTN_SUCCESS: null,
    LOAD_TTN_FAIL: null,
    LOAD_USER_REQUEST: null,
    LOAD_USER_SUCCESS: null,
    LOAD_USER_FAIL: null
});
